# TODO Maps are being staticly loaded. Need to find a way to generate a map via gps coordinates.

# Meta tag Images
meta-tag-image-01: "https://dl.dropboxusercontent.com/s/xqard10xkt2rhcw/IMG_0183.JPG?dl=0"
meta-tag-image-02: "https://dl.dropboxusercontent.com/s/2u507dwb1qksq53/IMG_0200.JPG?dl=0"
meta-tag-image-03: "https://dl.dropboxusercontent.com/s/1pqh9y88jcejmoh/IMG_0468.JPG?dl=0"
meta-tag-image-04: "https://dl.dropboxusercontent.com/s/s3fydx81ajpjvvk/IMG_0360.JPG?dl=0"

# Domain
domain: http://www.AlamoSqCondo.com

# Agent Info
agent-name: Naomi Lempert Lopez
agent-phone: 415 264 4093
agent-image-url: "http://static1.squarespace.com/static/552ec696e4b022da6171df15/t/55b910efe4b0ebf4ba6d1e5f/1438191860449/?format=500w"
agent-company: Coldwell Banker
agent-license: "BRE #01274031"
agent-logo: "images/Naomi-Logo.png"
agent-button-name-phone: "Naomi: 415 264 4093"

# Property Info
property-street-address: 1394 McAllister
property-full-address: 1394 McAllister. San Francisco, CA, 94115, United States
property-tag-line: "You're Home"
video-walkthrough-url: "https://dl.dropboxusercontent.com/s/0jjqtv1hkbncfnn/1394McAllisterWalkthrough.mp4"
list-price: $1,795,000
sqft: 2300
number-of-beds: 3 Beds
number-of-baths: 2.5 Baths # TODO Fix alignment of baths in html
matterport-embed-url: "https://my.matterport.com/show/?m=FhV2YDHCkDj"
property-description: Stunning full floor house-like Victorian condominium bathed in light with 11’ soaring ceilings and a modern open floorplan.  This beautiful home in an iconic turreted 1890’s corner building seamlessly blends period details and modern living with 3-4BR/2.5BA and 2,300sq ft of living area, bright open kitchen with downtown views, Viking gas range w/ hood, island w/ breakfast bar seating and Calcutta marble counters, 2.5 renovated bathrooms, in-unit laundry room,  rooms, coved ceilings, bay windows, wainscoting, moldings, and two fireplaces. The home is located in the hip Alamo Square neighborhood, just one block from Alamo Square Park, and close to many neighborhood amenities and shuttle stops.  Deeded private garage with a separate additional deeded storage/office/exercise room and wine cellar on ground level.

# Showings
showings: [
  {
    weekday: Saturday,
    date: October 24,
    time: "2:00-4:00PM"
  },
  { weekday: Sunday,
    date: October 25,
    time: "2:00-4:00PM"
  },
  {
    weekday: Tuesday,
    date:    October 27,
    time:    "11:00-12:30PM"
  },
  {
    weekday: Thursday,
    date:    October 29,
    time:    "5:30-6:30PM"
  }
]

# Highlight TODO figure out a way to do two lists side by side with only one highlight collection. Add Columns to Highlights
highlights-1: [
  attribute: Incredible Light & Views,
  attribute: Luxury Renovation,
  attribute: Open Floor Plan,
  attribute: 3-4BR/2.5BA,
]

highlights-2: [
  attribute: 11 Ft Ceilings,
  attribute: Independent Garage,
  attribute: "HOA Dues: $550/month",
  attribute: "Sq Ft: 2300 per tax records",
]

# Neighboorhood
neighboorhood-background-image-url: "http://img.sfbay.ca/home/wp-content/uploads/2013/08/alamo.jpg"
neighboorhood-name: Alamo Square
neighboorhood-description: Centered on its namesake park, Alamo Square provides snapshot-worthy views of San Francisco’s iconic Victorian architecture (you might recognize the “Painted Ladies” of Full House fame). Casual restaurants and cool shops add to the allure of this everyday neighborhood’s historic architecture and sweeping panoramas of Downtown. Not known for its rowdy nightlife scene, livelier neighborhoods like Haight-Ashbury and Hayes Valley are right next door.
map-longitude: "-122.434908"
map-latitude: "37.7784659"
map-zoom-level: 14

# Contact Section
contact-us-background-image-url: "http://www.bcxnews.org/photos/places/cities/us/ca/sf/parks/alamosq/AlamoSquare2008_3899B.jpg"
agent-website: "http://www.naomilopez.com/"

# TODO  Add gallery images here
# Master Living Room
gallery-image-01: "https://dl.dropboxusercontent.com/s/xqard10xkt2rhcw/IMG_0183.JPG?dl=0"
gallery-image-02: "https://dl.dropboxusercontent.com/s/e77xs42k3b8754y/IMG_0175.JPG?dl=0"
gallery-image-03: "https://dl.dropboxusercontent.com/s/ax6qzadbdgeb80e/IMG_0180.JPG?dl=0"

# Master
gallery-image-04: "https://dl.dropboxusercontent.com/s/2u507dwb1qksq53/IMG_0200.JPG?dl=0"
gallery-image-05: "https://dl.dropboxusercontent.com/s/6vf2anfla6gvbns/IMG_0195.JPG?dl=0"
gallery-image-06: "https://dl.dropboxusercontent.com/s/u6srj75ofhemrp6/IMG_0228.JPG?dl=0"

# Front
gallery-image-07: "https://dl.dropboxusercontent.com/s/1pqh9y88jcejmoh/IMG_0468.JPG?dl=0"
gallery-image-08: "https://dl.dropboxusercontent.com/s/0a2c1dwl8jcwm6s/IMG_0482.JPG?dl=0"
gallery-image-09: "https://dl.dropboxusercontent.com/s/00yyeb12o9mmkpv/IMG_0451.JPG?dl=0"

# Kitchen
gallery-image-10: "https://dl.dropboxusercontent.com/s/s3fydx81ajpjvvk/IMG_0360.JPG?dl=0"
gallery-image-11: "https://dl.dropboxusercontent.com/s/tsh57o1vxd92m5y/IMG_0397.JPG?dl=0"
gallery-image-12: "https://dl.dropboxusercontent.com/s/kobqxskw9m3pgd4/IMG_0386.JPG?dl=0"

gallery-image-13: "https://dl.dropboxusercontent.com/s/keo5fch7uqkt7sv/IMG_0441.JPG?dl=0"
gallery-image-14: "https://dl.dropboxusercontent.com/s/7trc3wshbghb9zw/IMG_0443.JPG?dl=0"
gallery-image-15: "https://dl.dropboxusercontent.com/s/tsh57o1vxd92m5y/IMG_0397.JPG?dl=0"

# Living Room
gallery-image-16: "https://dl.dropboxusercontent.com/s/o5nn27b5v4o2pjc/IMG_0325.JPG?dl=0"
gallery-image-17: "https://dl.dropboxusercontent.com/s/3ao0mt0701azuhv/IMG_0311.JPG?dl=0"
gallery-image-18: "https://dl.dropboxusercontent.com/s/9p051jdfy3ahsok/IMG_0321.JPG?dl=0"

# Yellow Bedroom
gallery-image-19: "https://dl.dropboxusercontent.com/s/l3oiaytvab9g037/IMG_0268.JPG?dl=0"
gallery-image-20: "https://dl.dropboxusercontent.com/s/8yleb4w4ku8rexy/IMG_0281.JPG?dl=0"
gallery-image-21: "https://dl.dropboxusercontent.com/s/4fdiyoyjjdxvxvs/IMG_0273.JPG?dl=0"

# Red Bedroom
gallery-image-22: "https://dl.dropboxusercontent.com/s/runjwdqk2kxhe2l/IMG_0247.JPG?dl=0"
gallery-image-23: "https://dl.dropboxusercontent.com/s/ryye13r0cj716ic/IMG_0257.JPG?dl=0"
gallery-image-24: "https://dl.dropboxusercontent.com/s/vxz8pcho9m2y0e4/IMG_0243.JPG?dl=0"

gallery-image-25: "https://dl.dropboxusercontent.com/s/eohiskl1an64zav/IMG_0426.JPG?dl=0"
gallery-image-26: "https://dl.dropboxusercontent.com/s/53xggec5e42g0e9/IMG_0414.JPG?dl=0"
gallery-image-27: "https://dl.dropboxusercontent.com/s/aklm1pqjf7gwuc0/IMG_0438.JPG?dl=0"

gallery-image-28: "https://dl.dropboxusercontent.com/s/srfyh7ov0ldnuql/IMG_0497.JPG?dl=0"
gallery-image-29:
gallery-image-30:
