# TODO Maps are being staticly loaded. Need to find a way to generate a map via gps coordinates.

# Meta tag Images
meta-tag-image-01: "https://dl.dropboxusercontent.com/s/56cpb9eb72ves83/IMG_9436.JPG"
meta-tag-image-02: "https://dl.dropboxusercontent.com/s/pcoxq8nv4rorbno/IMG_9446.JPG"
meta-tag-image-03:
meta-tag-image-04:

# Domain
domain: http://www.AlamoSqCondo.com

# Agent Info
agent-name: Naomi Lempert Lopez
agent-phone: 415 264 4093
agent-image-url: "http://static1.squarespace.com/static/552ec696e4b022da6171df15/t/55b910efe4b0ebf4ba6d1e5f/1438191860449/?format=500w"
agent-company: Coldwell Banker
agent-license: "BRE #01274031"
agent-logo: "images/Naomi-Logo.png"
agent-button-name-phone: "Naomi: 415 264 4093"

# Property Info
property-street-address: 1394 McAllister
property-full-address: 1394 McAllister. San Francisco, CA, 94115, United States
property-tag-line: "You're Home"
video-walkthrough-url: "https://dl.dropboxusercontent.com/s/jib8a2etgmwan96/1394McAllisterWalkthrough.mp4"
list-price: $??,000
sqft: 2300
number-of-beds: 3 Beds
number-of-baths: 2.5 Baths # TODO Fix alignment of baths in html
matterport-embed-url: "https://my.matterport.com/show/?m=FhV2YDHCkDj"
property-description: Property description here.

# Neighboorhood
neighboorhood-background-image-url: "http://img.sfbay.ca/home/wp-content/uploads/2013/08/alamo.jpg"
neighboorhood-name: Alamo Square
neighboorhood-description: Centered on its namesake park, Alamo Square provides snapshot-worthy views of San Francisco’s iconic Victorian architecture (you might recognize the “Painted Ladies” of Full House fame). Casual restaurants and cool shops add to the allure of this everyday neighborhood’s historic architecture and sweeping panoramas of Downtown. Not known for its rowdy nightlife scene, livelier neighborhoods like Haight-Ashbury and Hayes Valley are right next door.
map-longitude: "-122.434908"
map-latitude: "37.7784659"
map-zoom-level: 14

# Contact Section
contact-us-background-image-url: "http://www.bcxnews.org/photos/places/cities/us/ca/sf/parks/alamosq/AlamoSquare2008_3899B.jpg"
agent-website: "http://www.naomilopez.com/"

# TODO  Add gallery images here
gallery-image-01: "https://dl.dropboxusercontent.com/s/56cpb9eb72ves83/IMG_9436.JPG?dl=0"
gallery-image-02: "https://dl.dropboxusercontent.com/s/pcoxq8nv4rorbno/IMG_9446.JPG?dl=0"
